springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: INFO
    org.hibernate: INFO
    org.hibernate.engine.transaction.internal.TransactionImpl: INFO
    org.hibernate.stat: WARN

spring:
  jpa:
    properties:
      hibernate:
        generate_statistics: false
        session:
          events:
            log: false
        log_slow_query: 0

server:
  servlet:
    session:
      cookie:
        name: ${OAUTH_SESSION_COOKIE_NAME:__Secure-vote_oauth}
        http-only: true
        secure: true
        same-site: Lax

app:
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS}
    jwt:
      secret: ${JWT_SECRET}
    refresh-token:
      cookie-name: ${REFRESH_COOKIE_NAME:__Secure-vote_refresh}
      secure: true
      same-site: Strict
